# This file is used to configure your services on Render.
# For more information, see https://render.com/docs/yaml-spec
services:
  
  # A Web Service
  - type: web
    name: estudiante-sistema # Replace with your project name, e.g., "asistencia-escolar"
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn asistencia_escolar.wsgi" # Replace 'asistencia_escolar' with your project's main module name
    envVars:
      - key: postgresql://admin:lLhazxynpcriTCRUb3Q2dg7ztFlfFCLz@dpg-d60odcd6ubrc739c9ke0-a/estudiante_db_njnk
        fromDatabase:
          name: estudiante_db 
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4 # Adjust based on your instance size
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS # Add your Render URL here after deployment
        value: "estudiante-sistema.onrender.com" # Replace with your actual Render service URL
